# Configuration for welcome bot - https://github.com/behaviorbot/welcome
########################################################################################

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
  üíñ **Thank you for opening your first pull request in this repository!** üíñ

  A few things to keep in mind:

  * [Authorship Guidelines](https://github.com/fatiando/community/blob/main/AUTHORSHIP.md): Our rules for giving you credit for your contributions, including authorship on publications and [Zenodo](https://zenodo.org/communities/fatiando) archives.
  * [Code of Conduct](https://github.com/fatiando/community/blob/main/CODE_OF_CONDUCT.md): How we expect people to interact in our projects.
  
  ‚≠ê **No matter what, we are really grateful that you put in the effort to do this!** ‚≠ê

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
  üéâ **Congrats on merging your first pull request and welcome to the team!** üéâ

  **If you would like to be added as a author** on the [Zenodo](https://zenodo.org/communities/fatiando) archive of the next release, make sure that you have added your full name, affiliation, and [ORCID](https://orcid.org) (optional) to the `AUTHORS.md` file of this repository.

  We hope that this was a good experience for you. Let us know if there is any way that the contributing process could be improved.
